#!/bin/bash

# Here we set some PATH's and environment variables for script execution
PATH=$PATH:$HOME/bin:/usr:/bin:/sbin:/usr/bin:/usr/sbin:

export PATH

distro='tech@techdataserv.net' #Define the distro email address the change notification goes too
ccdistro='adminonduty@techdataserv.net'
echocmd="/bin/echo"
CommandFile="/usr/local/nagios/var/rw/nagios.cmd"

# get the current date/time in seconds since UNIX epoch
datetimestamp=$(date +%s)
datetime=$(date)

cmdline="[$datetimestamp]"
SVCUP="STOP_EXECUTING_SVC_CHECKS;"
SVCDOWN="START_EXECUTING_SVC_CHECKS;"
NOTIFON="ENABLE_NOTIFICATIONS;"
NOTIFOFF="DISABLE_NOTIFICATIONS;"

$echocmd $cmdline $SVCUP >> $CommandFile
$echocmd $cmdline $NOTIFOFF >> $CommandFile

crontab -r

echo "*/15 * * * * /usr/local/nagioshome/rsync.pull-nagios.sh >/dev/null 2>&1" > /usr/local/nagioshome/cron.tmp
crontab /usr/local/nagioshome/cron.tmp
rm -rf /usr/local/nagioshome/cron.tmp

echo "Primary Nagios appears to have recovered, assuming slave role and enabling sync..." |mail -s "Primary Nagios Recovery Alert" $distro -c $ccdistro
exit
